# repo-2/.github/workflows/main-build-deploy.yaml
name: Main Build & Deploy

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language to build'
        required: true
        type: choice
        options:
          - java
          - python
      env:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
      upload_artifact:
        description: 'Upload Artifact?'
        required: false
        default: 'false'
        type: boolean

jobs:
  call-reusable-workflow:
    uses: pkseaws/repo-1/.github/workflows/unified-build-deployment.yaml@main
    with:
      language: ${{ inputs.language }}
      env: ${{ inputs.env }}
      upload_artifact: ${{ inputs.upload_artifact }}
    
